server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG


spring:
  # 다국어 파일 설정
  messages:
    basename: messages

  # Spring Security
  security:
    user:
      name: user
      password: 12345678

  #h2 setting -> 최신 h2 에서는 데이터베이스를 미리 생성하는것을 방지하도록 설정되어 있어서
  datasource:
    url: jdbc:h2:mem:testdb

  # jpa log
  jpa:
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

# Monitoring by Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level:
  org.hibernate.SQL: debug    #jpa/hibernate 가 생성하는 모든 sql을 눈으로 확인가능
  org.hibernate.type: trace  #SQL 실행 파라미터를 로그로 남긴다