server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG


spring:
  # 다국어 파일 설정
  messages:
    basename: messages

  # Spring Security
  security:
    user:
      name: user
      password: 12345678

# Monitoring by Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"




